apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
type: Opaque
data:
  mongo-user: bW9uZ291c2Vy #echo -n mongouser | base64 works in ubuntu to covernt text in base64
  mongo-password: bW9uZ29wYXNzd29yZA==